### PR TITLE
you forgor

### PR DESCRIPTION
**Pull request by Megarion**
wtf whydid you put anchor tags in a meta tag attribute

### CODE REVIEW

**Comment by sertdfyguhi** [comment]
this still wont fix it

**Comment by sertdfyguhi** [comment]
because tk_game_description is for the meta tag and the p tag

**Comment by sertdfyguhi** [comment]
and the anchor tag has double quotes that are unescaped inside double quotes

**Comment by Megarion** [comment]
ok but where is the tk_game_description here

**Comment by sertdfyguhi** [comment]
config.csv

**Comment by Megarion** [comment]
what

**Comment by sertdfyguhi** [comment]
what

**Comment by Megarion** [comment]
what does it have to do with the index.html file

**Comment by sertdfyguhi** [comment]
its being generated

**Comment by Megarion** [comment]
ok wait l.et me take a look

**Comment by sertdfyguhi** [comment]
lemme fix it

**Comment by Megarion** [comment]
you should be able to do a better job 🥶

**Pull request closed without merging**
